language: php

sudo: false
# Fixes "HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`."
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: composer install --prefer-source

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script: PHPRC=$PWD/lib/Transphpile/Tests/phprc vendor/bin/phpunit
